<?php 
// Configuration array
$accolore_config['wp-al-settings-demo'] = array(
	'title'             => 'WP Accolore Settings Demo',
	'version'           => '1.0',
	'text_domain'       => 'wp-al-settings-demo',
	'prefix'            => 'wpals',
	'tgmpa_plugins'     => false,
	'documentation_tab' => array(
		'title' => esc_html__( 'Documentation external link', 'wp-al-settings-demo' ),
		'url'   => esc_html__('http://www.google.com'),
	),
	'demo_page' => array(
		'title'   => 'WP Accolore Settings Demo Page',
		'name'    => 'wpals-demo-page',
		'content' => '<p>This content will be added to the page. You can use placeholders to insert images or other files.</p><img src="{{1}}" title="Image 1" /> <img src="{{2}}" title="Image 2" />',
		'media'   => array(
			1 => 'https://placehold.co/600x400',
			2 => 'https://placehold.co/200x200',
		),
	),
	'menu' => array(
		'page_title' => 'WP Accolore Settings Demo',
		'menu_title' => 'WP Settings Demo',
		'capability' => 'manage_options',
		'icon'       => 'dashicons-buddicons-replies',
		'position'   => 100,
	),
	'sections' => array(
		array(
			'id'      => 'basic',
			'title'   => esc_html__( 'Basic fields', 'wp-al-settings-demo' ),
			'default' => true,
			'fields'  => array(
				array(
					'id'       => 'raw_field',
					'type'     => 'raw',
					'title'    => esc_html__( 'Raw field', 'wp-al-settings-demo' ),
					'content'  => '<img src="https://placehold.co/400x300" />',
				),
				array(
					'id'       => 'switch_field1',
					'type'     => 'switch',
					'title'    => esc_html__( 'Switch field', 'wp-al-settings-demo' ),
					'subtitle' => esc_html__( 'Field subtitle.', 'wp-al-settings-demo' ),
					'desc'     => '<img src="https://placehold.co/48x48" />',
					'default'  => 0,
					'on'       => esc_html__( 'Yes', 'wp-al-settings-demo' ),
					'off'      => esc_html__( 'No', 'wp-al-settings-demo' ),
				),
				array(
					'id'       => 'switch_field2',
					'type'     => 'switch',
					'title'    => esc_html__( 'Switch field', 'wp-al-settings-demo' ),
					'subtitle' => esc_html__( 'Field subtitle.', 'wp-al-settings-demo' ),
					'desc'     => esc_html__( 'Field description.', 'wp-al-settings-demo' ),
					'default'  => 1,
					'on'       => esc_html__( 'Selected', 'wp-al-settings-demo' ),
					'off'      => esc_html__( 'Unselected', 'wp-al-settings-demo' ),
				),
				array(
					'id'       => 'switch_field2',
					'type'     => 'switch',
					'title'    => esc_html__( 'Switch field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 1,
					'on'       => esc_html__( 'Selected', 'wp-al-settings-demo' ),
					'off'      => esc_html__( 'Unselected', 'wp-al-settings-demo' ),
				),
				array(
					'id'       => 'select_field',
					'type'     => 'select',
					'title'    => esc_html__( 'Select field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 'value1',
					'options'  => array(
						'value1' => esc_html__( 'Value 1', 'wp-al-settings-demo' ),
						'value2' => esc_html__( 'Value 2', 'wp-al-settings-demo' ),
						'value3' => esc_html__( 'Value 3', 'wp-al-settings-demo' ),
					),
				),
				array(
					'id'       => 'text_field1',
					'type'     => 'text',
					'title'    => esc_html__( 'Text field', 'wp-al-settings-demo' ),
					'subtitle' => esc_html__( 'Field subtitle.', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 'Default value',
				),
				array(
					'id'       => 'text_field2',
					'type'     => 'text',
					'title'    => esc_html__( 'Text field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => '',
				),
				array(
					'id'       => 'textarea_field',
					'type'     => 'textarea',
					'title'    => esc_html__( 'Textarea field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 'default value',
				),
				array(
					'id'       => 'slider_field',
					'type'     => 'slider',
					'title'    => esc_html__( 'Slider field', 'wp-al-settings-demo' ),
					'subtitle' => esc_html__( 'A numeric value managed by a linear slider.', 'wp-al-settings-demo' ),
					'desc'     => '',
					'default'  => 10,
					'min'      => 5,
					'step'     => 1,
					'max'      => 100,
				),
				array(
					'id'           => 'media_image_field',
					'type'         => 'media_image',
					'title'        => esc_html__( 'Media image field', 'wp-al-settings-demo' ),
					'subtitle'     => esc_html__( 'Contain an image selected from media library or uploaded.', 'wp-al-settings-demo' ),
					'desc'         => '',
					'default'      => plugin_dir_url( __FILE__ ) . 'admin/images/placeholder.png',
				),
				array(
					'id'           => 'media_other_field',
					'type'         => 'media_other',
					'title'        => esc_html__( 'Media other field', 'wp-al-settings-demo' ),
					'subtitle'     => esc_html__( 'Contain an media (not an image) selected from media library or uploaded. When selected the media name will be displayed in the preview.', 'wp-al-settings-demo' ),
					'desc'         => '',
					'default'      => '',
					'mime_type'    => false, // "'audio','video'", set to false if all mime types are allowed
				),
				array(
					'id'       => 'reset_field',
					'type'     => 'reset',
					'title'    => '',
					'default'  => '',
				),
			),
		),
		array(
			'id'     => 'styling',
			'title'  => esc_html__( 'Styling fields', 'wp-al-settings-demo' ),
			'default' => false,
			'fields'  => array(
				array(
					'id'       => 'link_color_field',
					'type'     => 'link_color',
					'title'    => esc_html__( 'Link color field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'selector' => array(
						'regular' => true,
						'hover'   => true,
						'active'  => true,
						'visited' => true,
					),
					'default' => array(
						'regular' => '#eeeeee',
						'hover'   => '#ffffff',
						'active'  => '#ff0000',
						'visited' => '#00ffff',
					),
					'output'   => array(
						'a',
					),
				),
				array(
					'id'       => 'background_color_field',
					'type'     => 'background_color',
					'title'    => esc_html__( 'Background color field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => '#333333',
					'output'   => array(
						'a',
						'a:selected',
						'a:hover',
						'a:active',
						'a:focus',
					),
				),
				array(
					'id'             => 'typography_field1',
					'type'           => 'typography',
					'title'          => esc_html__('Typography field', 'wp-al-settings-demo'),
					'subtitle'       => '',
					'desc'           => '',
					'google_api_key' => 'AIzaSyC3nCnaCoEz6-iaMd2OQmYxw4dOCKaIlUI',
					'default'        => array(
						'family' => 'Courier New',
						'color'  => '#00f0f0',
						'size'   => '12px',
						'weight' => '400',
					),
					'output' => array(
						'p',
					),
				),
				array(
					'id'             => 'typography_field2',
					'type'           => 'typography',
					'title'          => esc_html__('Typography field', 'wp-al-settings-demo'),
					'subtitle'       => '',
					'desc'           => '',
					'google_api_key' => 'AIzaSyC3nCnaCoEz6-iaMd2OQmYxw4dOCKaIlUI',
					'default'        => array(
						'family' => 'Arial',
						'color'  => '#f0f0ff',
						'size'   => '20px',
						'weight' => '600',
					),
					'output'   => array(
						'h1',
						'h2',
						'h3',
						'h4',
						'h5',
						'h6',
					),
				),
				array(
					'id'       => 'color_field1',
					'type'     => 'color',
					'title'    => esc_html__( 'Color field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => '#2776c8',
					'output'   => array(
						'background-color' => 'p'
					),
					'alpha'    => true,
				),
				array(
					'id'       => 'color_field2',
					'type'     => 'color',
					'title'    => esc_html__( 'Color field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'output'   => array(
						'background-color' => 'h1'
					),
					'default'  => 'rgba(0,0,0,0.7)',
					'alpha'    => true,
				),
				array(
					'id'       => 'spacing_field1',
					'type'     => 'spacing',
					'title'    => esc_html__( 'Spacing field (padding)', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'subtype'  => 'padding',
					'default'  => array(
						'top'    => 10,
						'right'  => 10,
						'bottom' => 10,
						'left'   => 10,
					),
					'output'   => array(
						'div'
					),
				),
				array(
					'id'       => 'spacing_field2',
					'type'     => 'spacing',
					'title'    => esc_html__( 'Spacing field (margin)', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'subtype'  => 'margin',
					'default'  => array(
						'top'    => 10,
						'right'  => 10,
						'bottom' => 10,
						'left'   => 10,
					),
					'output'   => array(
						'div'
					),
				),
				array(
					'id'       => 'reset_field',
					'type'     => 'reset',
					'title'    => '',
					'default'  => '',
				),
			),
		),
		array(
			'id'     => 'visibility',
			'title'  => esc_html__( 'Field visibility', 'wp-al-settings-demo' ),
			'default' => false,
			'fields'  => array(
				array(
					'id'       => 'switch_field_master',
					'type'     => 'switch',
					'title'    => esc_html__( 'Switch field', 'wp-al-settings-demo' ),
					'subtitle' => esc_html__( 'If this field is set to Selected, other fields will be displayed', 'wp-al-settings-demo' ),
					'desc'     => '',
					'default'  => 0,
					'on'       => esc_html__( 'Selected', 'wp-al-settings-demo' ),
					'off'      => esc_html__( 'Unselected', 'wp-al-settings-demo' ),
				),
				array(
					'id'       => 'text_field_slave',
					'type'     => 'text',
					'title'    => esc_html__( 'Text field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 'Default value',
					'required' => array(
						'target'   => 'switch_field_master',
						'operator' => '=', // =, <, >, !=
						'value'    => '1',
					),
				),				
				array(
					'id'       => 'slider_field_slave',
					'type'     => 'slider',
					'title'    => esc_html__( 'Slider field', 'wp-al-settings-demo' ),
					'subtitle' => '',
					'desc'     => '',
					'default'  => 10,
					'min'      => 5,
					'step'     => 1,
					'max'      => 100,
					'required' => array(
						'target'   => 'switch_field_master',
						'operator' => '=', // =, <, >, !=
						'value'    => '1',
					),

				),
				array(
					'id'       => 'reset_field',
					'type'     => 'reset',
					'title'    => '',
					'default'  => '',
				),
			),
		),
		array(
			'id'     => 'dev',
			'title'  => esc_html__( 'Dev fields', 'wp-al-settings-demo' ),
			'default' => false,
			'fields'  => array(
				
			),
		),		
	),
);